eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763

spring:
  jmx:
    default-domain: localhost
  application:
    name: sc-freemarker
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    suffix: .ftl
    templateLoaderPath: classpath:/static/
    expose-spring-macro-helpers: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Hyt
    username: root
    password: root


mybatis:
  mapperLocations : classpath*:com/hyt/mapper/*.xml
  typeAliasesPackage : com.hyt.entity